 CXX = g++
 EXE = Renderer.exe
 
 INC_DIRS = -I./include
 CXXFLAGS = $(INC_DIRS) -std=c++11
 LDFLAGS = -L./lib
 LDLIBS = -lglfw -lglew -lopengl32
 
 LINK = $(CXX) $(LDFLAGS) $(LDLIBS) -o
 COMPILE = $(CXX) $(CXXFLAGS) -c
 
 FILES = main.o vec4.o vec3.o vec2.o mat2.o mat3.o mat4.o window.o camera.o input.o
 
 .PHONY: clean all run debug release
 
 all: $(EXE)
 
debug:	CXXFLAGS += -DDEBUG -g
debug:	$(EXE)

release: CXXFLAGS += -O3
release: $(EXE)
 
clean:
	rm -r *.o *.exe *.log

run:	$(EXE)
	clear
	./$(EXE) $(SCENE)

$(EXE): 	$(FILES)
	$(LINK) $(EXE) $(FILES)

%.o: 	%.cpp %.h
	$(COMPILE) $<